INFO 09-11 15:42:47 [__init__.py:36] Available plugins for group vllm.platform_plugins:
INFO 09-11 15:42:47 [__init__.py:38] - ascend -> vllm_ascend:register
INFO 09-11 15:42:47 [__init__.py:41] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 09-11 15:42:47 [__init__.py:232] Platform plugin ascend is activated
WARNING 09-11 15:42:48 [_custom_ops.py:20] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 09-11 15:42:48 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 09-11 15:42:49 [registry.py:477] Model architecture DeepSeekMTPModel is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_mtp:CustomDeepSeekMTP.
WARNING 09-11 15:42:49 [registry.py:477] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:AscendQwen2VLForConditionalGeneration.
WARNING 09-11 15:42:49 [registry.py:477] Model architecture Qwen2_5_VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_5_vl:AscendQwen2_5_VLForConditionalGeneration.
WARNING 09-11 15:42:49 [registry.py:477] Model architecture DeepseekV2ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV2ForCausalLM.
WARNING 09-11 15:42:49 [registry.py:477] Model architecture DeepseekV3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v3:CustomDeepseekV3ForCausalLM.
WARNING 09-11 15:42:49 [registry.py:477] Model architecture Qwen3MoeForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3_moe:CustomQwen3MoeForCausalLM.
WARNING 09-11 15:42:49 [registry.py:477] Model architecture Qwen3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3:CustomQwen3ForCausalLM.
INFO 09-11 15:42:49 [utils.py:328] non-default args: {'trust_remote_code': True, 'max_model_len': 4096, 'tensor_parallel_size': 2, 'context_parallel_size': 4, 'enable_sequence_parallel': True, 'enable_expert_parallel': True, 'block_size': 128, 'enable_prefix_caching': False, 'max_num_batched_tokens': 1024, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': True, 'additional_config': {'ascend_scheduler_config': {'enabled': True}}, 'model': '/home/DeepSeek-V2-Lite'}
INFO 09-11 15:42:49 [config.py:234] Replacing legacy 'type' key with 'rope_type'
INFO 09-11 15:42:57 [__init__.py:744] Resolved architecture: DeepseekV2ForCausalLM
INFO 09-11 15:42:57 [__init__.py:1773] Using max model len 4096
INFO 09-11 15:42:57 [config.py:234] Replacing legacy 'type' key with 'rope_type'
INFO 09-11 15:42:57 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=1024.
INFO 09-11 15:42:57 [platform.py:144] Compilation disabled, using eager mode by default
WARNING 09-11 15:42:57 [platform.py:162] compilation_config.level = CompilationLevel.NO_COMPILATION is set, Setting CUDAGraphMode to NONE
[1;36m(EngineCore_0 pid=593469)[0;0m INFO 09-11 15:42:57 [core.py:648] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=593469)[0;0m INFO 09-11 15:42:57 [core.py:75] Initializing a V1 LLM engine (v0.1.dev9077+g05579c458) with config: model='/home/DeepSeek-V2-Lite', speculative_config=None, tokenizer='/home/DeepSeek-V2-Lite', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=npu, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/home/DeepSeek-V2-Lite, enable_prefix_caching=False, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["all"],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=593469)[0;0m WARNING 09-11 15:42:57 [multiproc_worker_utils.py:273] Reducing Torch parallelism from 640 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[1;36m(EngineCore_0 pid=593469)[0;0m INFO 09-11 15:42:57 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1, 2, 3, 4, 5, 6, 7], buffer_handle=(8, 16777216, 10, 'psm_37f98fdf'), local_subscribe_addr='ipc:///tmp/04558540-4fdd-4cb8-8c2a-90c55fbf6629', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m INFO 09-11 15:43:10 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_f8698fb1'), local_subscribe_addr='ipc:///tmp/21a6fd88-6897-44f2-89f6-ccc1dd824045', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593509)[0;0m INFO 09-11 15:43:10 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_bd2c7e2b'), local_subscribe_addr='ipc:///tmp/58ca0278-5994-46b1-a767-88313d9dc9d5', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593481)[0;0m INFO 09-11 15:43:10 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_1cac8047'), local_subscribe_addr='ipc:///tmp/5e8f7718-8c05-4853-a8c3-acadb1b21f6c', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593495)[0;0m INFO 09-11 15:43:11 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_e07a8615'), local_subscribe_addr='ipc:///tmp/e7d140c4-3a3d-4b89-9d07-b7a80fddb573', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593506)[0;0m INFO 09-11 15:43:13 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_2339e956'), local_subscribe_addr='ipc:///tmp/458eea7a-867c-48bb-b666-22d5e8d89077', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593491)[0;0m INFO 09-11 15:43:13 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_aa425f66'), local_subscribe_addr='ipc:///tmp/5ffdcb79-701e-4017-9792-7ac94824e81c', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593500)[0;0m INFO 09-11 15:43:13 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_14a2011b'), local_subscribe_addr='ipc:///tmp/9080d31f-40e7-4477-a23b-d32fb3d5b67d', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m INFO 09-11 15:43:14 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_3b6104f4'), local_subscribe_addr='ipc:///tmp/35b5d83b-4980-4ae8-b25e-3508dab701c8', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593495)[0;0m INFO 09-11 15:43:22 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_e5d249f6'), local_subscribe_addr='ipc:///tmp/daea9447-017a-4c4c-a6c1-5db7c4cd0fa6', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m INFO 09-11 15:43:22 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_7f353f41'), local_subscribe_addr='ipc:///tmp/6f015245-a48d-438a-9872-b8e0cfacdc08', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m INFO 09-11 15:43:22 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_cd328941'), local_subscribe_addr='ipc:///tmp/54b4c994-7765-42e2-b451-01c93de99700', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593506)[0;0m INFO 09-11 15:43:22 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_480a58bc'), local_subscribe_addr='ipc:///tmp/3197e849-fa16-41e2-a2c3-436252788f91', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593495)[0;0m INFO 09-11 15:43:22 [parallel_state.py:1163] rank 4 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 4, CP rank 2
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m INFO 09-11 15:43:22 [parallel_state.py:1163] rank 0 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0, CP rank 0
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m INFO 09-11 15:43:22 [parallel_state.py:1163] rank 2 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 2, CP rank 1
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593506)[0;0m INFO 09-11 15:43:22 [parallel_state.py:1163] rank 6 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 6, CP rank 3
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593500)[0;0m INFO 09-11 15:43:22 [parallel_state.py:1163] rank 5 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 5, CP rank 2
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593491)[0;0m INFO 09-11 15:43:22 [parallel_state.py:1163] rank 3 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 3, CP rank 1
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593481)[0;0m INFO 09-11 15:43:22 [parallel_state.py:1163] rank 1 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1, CP rank 0
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593509)[0;0m INFO 09-11 15:43:22 [parallel_state.py:1163] rank 7 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 7, CP rank 3
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593491)[0;0m INFO 09-11 15:43:22 [model_runner_v1.py:2585] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m INFO 09-11 15:43:22 [model_runner_v1.py:2585] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593481)[0;0m INFO 09-11 15:43:22 [model_runner_v1.py:2585] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m INFO 09-11 15:43:22 [model_runner_v1.py:2585] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593509)[0;0m INFO 09-11 15:43:22 [model_runner_v1.py:2585] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593500)[0;0m INFO 09-11 15:43:22 [model_runner_v1.py:2585] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593506)[0;0m INFO 09-11 15:43:22 [model_runner_v1.py:2585] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593495)[0;0m INFO 09-11 15:43:22 [model_runner_v1.py:2585] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593491)[0;0m INFO 09-11 15:43:22 [layer.py:845] [EP Rank 3/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->24, 1->25, 2->26, 3->27, 4->28, 5->29, 6->30, 7->31.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m INFO 09-11 15:43:23 [layer.py:845] [EP Rank 2/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->16, 1->17, 2->18, 3->19, 4->20, 5->21, 6->22, 7->23.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m INFO 09-11 15:43:23 [layer.py:845] [EP Rank 0/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->0, 1->1, 2->2, 3->3, 4->4, 5->5, 6->6, 7->7.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593500)[0;0m INFO 09-11 15:43:23 [layer.py:845] [EP Rank 5/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->40, 1->41, 2->42, 3->43, 4->44, 5->45, 6->46, 7->47.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593506)[0;0m INFO 09-11 15:43:23 [layer.py:845] [EP Rank 6/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->48, 1->49, 2->50, 3->51, 4->52, 5->53, 6->54, 7->55.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593509)[0;0m INFO 09-11 15:43:23 [layer.py:845] [EP Rank 7/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->56, 1->57, 2->58, 3->59, 4->60, 5->61, 6->62, 7->63.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP1 pid=593481)[0;0m INFO 09-11 15:43:23 [layer.py:845] [EP Rank 1/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->8, 1->9, 2->10, 3->11, 4->12, 5->13, 6->14, 7->15.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593495)[0;0m INFO 09-11 15:43:23 [layer.py:845] [EP Rank 4/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->32, 1->33, 2->34, 3->35, 4->36, 5->37, 6->38, 7->39.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] WorkerProc failed to start.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 550, in worker_main
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     worker = WorkerProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 419, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.worker.load_model()
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/worker/worker_v1.py", line 241, in load_model
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.model_runner.load_model()
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 2588, in load_model
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.model = get_model(vllm_config=self.vllm_config)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/model_loader/__init__.py", line 118, in get_model
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     return loader.load_model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/model_loader/base_loader.py", line 44, in load_model
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     model = initialize_model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/model_loader/utils.py", line 63, in initialize_model
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     return model_class(vllm_config=vllm_config, prefix=prefix)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 878, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.model = CustomDeepseekV2Model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 800, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.start_layer, self.end_layer, self.layers = make_layers(
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                                                     ^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/models/utils.py", line 642, in make_layers
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     [PPMissingLayer() for _ in range(start_layer)] + [
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                                                      ^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/models/utils.py", line 643, in <listcomp>
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 802, in <lambda>
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     lambda prefix: CustomDeepseekV2DecoderLayer(
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 664, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.mlp = CustomDeepseekV2MoE(
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                ^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 337, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.experts = AscendFusedMoE(
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                    ^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/ops/fused_moe.py", line 336, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.quant_method = AscendUnquantizedFusedMoEMethod(moe)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/ops/fused_moe.py", line 125, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.moe_all_to_all_group_name = backend.get_hccl_comm_name(
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] RuntimeError: create_config:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:148 HCCL function error: hcclCommInitRootInfoConfig(numRanks, &rootInfo, rank, config, &(comm->hcclComm_)), error code is 7
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] [ERROR] 2025-09-11-15:43:23 (PID:593476, Device:0, RankID:-1) ERR02200 DIST call hccl api failed.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] EJ0003: [PID: 593476] 2025-09-11-15:43:23.871.937 Failed to bind the IP port. Reason: The IP address and port have been bound already.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593476)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] 
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] WorkerProc failed to start.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 550, in worker_main
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     worker = WorkerProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 419, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.worker.load_model()
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/worker/worker_v1.py", line 241, in load_model
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.model_runner.load_model()
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 2588, in load_model
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.model = get_model(vllm_config=self.vllm_config)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/model_loader/__init__.py", line 118, in get_model
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     return loader.load_model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/model_loader/base_loader.py", line 44, in load_model
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     model = initialize_model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/model_loader/utils.py", line 63, in initialize_model
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     return model_class(vllm_config=vllm_config, prefix=prefix)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 878, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.model = CustomDeepseekV2Model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 800, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.start_layer, self.end_layer, self.layers = make_layers(
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                                                     ^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/models/utils.py", line 642, in make_layers
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     [PPMissingLayer() for _ in range(start_layer)] + [
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                                                      ^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/models/utils.py", line 643, in <listcomp>
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 802, in <lambda>
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     lambda prefix: CustomDeepseekV2DecoderLayer(
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 664, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.mlp = CustomDeepseekV2MoE(
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                ^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 337, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.experts = AscendFusedMoE(
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                    ^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/ops/fused_moe.py", line 336, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.quant_method = AscendUnquantizedFusedMoEMethod(moe)
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/ops/fused_moe.py", line 125, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]     self.moe_all_to_all_group_name = backend.get_hccl_comm_name(
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576]                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] RuntimeError: create_config:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:148 HCCL function error: hcclCommInitRootInfoConfig(numRanks, &rootInfo, rank, config, &(comm->hcclComm_)), error code is 7
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] [ERROR] 2025-09-11-15:43:24 (PID:593486, Device:2, RankID:-1) ERR02200 DIST call hccl api failed.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] EJ0003: [PID: 593486] 2025-09-11-15:43:24.091.431 Failed to bind the IP port. Reason: The IP address and port have been bound already.
[1;36m(EngineCore_0 pid=593469)[0;0m [1;36m(VllmWorker TP0 pid=593486)[0;0m ERROR 09-11 15:43:24 [multiproc_executor.py:576] 
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712] EngineCore failed to start.
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]   File "/home/vllm/vllm/v1/engine/core.py", line 703, in run_engine_core
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]   File "/home/vllm/vllm/v1/engine/core.py", line 504, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]   File "/home/vllm/vllm/v1/engine/core.py", line 81, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]   File "/home/vllm/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]     self._init_executor()
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 98, in _init_executor
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]     self.workers = WorkerProc.wait_for_ready(unready_workers)
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 489, in wait_for_ready
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712]     raise e from None
[1;36m(EngineCore_0 pid=593469)[0;0m ERROR 09-11 15:43:26 [core.py:712] Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
[ERROR] 2025-09-11-15:43:26 (PID:593197, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
