INFO 09-10 14:56:10 [__init__.py:36] Available plugins for group vllm.platform_plugins:
INFO 09-10 14:56:10 [__init__.py:38] - ascend -> vllm_ascend:register
INFO 09-10 14:56:10 [__init__.py:41] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 09-10 14:56:10 [__init__.py:232] Platform plugin ascend is activated
WARNING 09-10 14:56:11 [_custom_ops.py:20] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 09-10 14:56:12 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 09-10 14:56:12 [registry.py:477] Model architecture DeepSeekMTPModel is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_mtp:CustomDeepSeekMTP.
WARNING 09-10 14:56:12 [registry.py:477] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:AscendQwen2VLForConditionalGeneration.
WARNING 09-10 14:56:12 [registry.py:477] Model architecture Qwen2_5_VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_5_vl:AscendQwen2_5_VLForConditionalGeneration.
WARNING 09-10 14:56:12 [registry.py:477] Model architecture DeepseekV2ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV2ForCausalLM.
WARNING 09-10 14:56:12 [registry.py:477] Model architecture DeepseekV3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v3:CustomDeepseekV3ForCausalLM.
WARNING 09-10 14:56:12 [registry.py:477] Model architecture Qwen3MoeForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3_moe:CustomQwen3MoeForCausalLM.
WARNING 09-10 14:56:12 [registry.py:477] Model architecture Qwen3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3:CustomQwen3ForCausalLM.
INFO 09-10 14:56:12 [utils.py:328] non-default args: {'trust_remote_code': True, 'max_model_len': 4096, 'tensor_parallel_size': 2, 'context_parallel_size': 4, 'enable_sequence_parallel': True, 'enable_expert_parallel': True, 'block_size': 128, 'enable_prefix_caching': False, 'max_num_batched_tokens': 1024, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': True, 'additional_config': {'ascend_scheduler_config': {'enabled': True}}, 'model': '/home/DeepSeek-V2-Lite'}
INFO 09-10 14:56:12 [config.py:234] Replacing legacy 'type' key with 'rope_type'
INFO 09-10 14:56:20 [__init__.py:744] Resolved architecture: DeepseekV2ForCausalLM
INFO 09-10 14:56:20 [__init__.py:1773] Using max model len 4096
INFO 09-10 14:56:20 [config.py:234] Replacing legacy 'type' key with 'rope_type'
INFO 09-10 14:56:20 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=1024.
INFO 09-10 14:56:20 [platform.py:144] Compilation disabled, using eager mode by default
WARNING 09-10 14:56:20 [platform.py:162] compilation_config.level = CompilationLevel.NO_COMPILATION is set, Setting CUDAGraphMode to NONE
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:56:21 [core.py:648] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:56:21 [core.py:75] Initializing a V1 LLM engine (v0.1.dev9076+ge80ce3c81) with config: model='/home/DeepSeek-V2-Lite', speculative_config=None, tokenizer='/home/DeepSeek-V2-Lite', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=npu, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/home/DeepSeek-V2-Lite, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["all"],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=738105)[0;0m WARNING 09-10 14:56:21 [multiproc_worker_utils.py:273] Reducing Torch parallelism from 640 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:56:21 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1, 2, 3, 4, 5, 6, 7], buffer_handle=(8, 16777216, 10, 'psm_010458af'), local_subscribe_addr='ipc:///tmp/c6a68e50-9bd4-49d1-b854-5d1a423bd4a0', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m INFO 09-10 14:56:47 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_18641b7a'), local_subscribe_addr='ipc:///tmp/f3e9764c-282e-4161-8b53-ce53bbe4e07c', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m INFO 09-10 14:56:47 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_cc6ef2e1'), local_subscribe_addr='ipc:///tmp/505cd535-1ee6-408d-bf9f-182cd735a9b2', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738137)[0;0m INFO 09-10 14:56:48 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_bbe0ed3e'), local_subscribe_addr='ipc:///tmp/48a1b4a5-a5d6-4074-b400-203b7e07de30', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738122)[0;0m INFO 09-10 14:56:49 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_a89bf987'), local_subscribe_addr='ipc:///tmp/ff26223f-02f5-4d98-bbdf-5abc60862f8a', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738127)[0;0m INFO 09-10 14:56:49 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_3c50a061'), local_subscribe_addr='ipc:///tmp/0f1296ae-05fc-4f23-839f-720ed4ebf672', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738132)[0;0m INFO 09-10 14:56:49 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_b9416071'), local_subscribe_addr='ipc:///tmp/c1b1378f-d158-4e43-bd71-67d45d0784f7', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738147)[0;0m INFO 09-10 14:56:50 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_0e91900e'), local_subscribe_addr='ipc:///tmp/595c6993-768c-4d53-90d1-3af6558813a8', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738142)[0;0m INFO 09-10 14:56:50 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_843fbc36'), local_subscribe_addr='ipc:///tmp/b38b7ca5-6fa3-44c4-be1b-49bec4358038', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m INFO 09-10 14:56:59 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_07b22d90'), local_subscribe_addr='ipc:///tmp/1654e31e-7ad0-4129-a346-b9d884cb0463', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738142)[0;0m INFO 09-10 14:56:59 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_a191e9d0'), local_subscribe_addr='ipc:///tmp/6097f737-e3ff-4b2d-ad69-d5d52c804687', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738122)[0;0m INFO 09-10 14:56:59 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_f8a45a53'), local_subscribe_addr='ipc:///tmp/81ae8643-4a65-4ae9-8c94-076d2fbb86e6', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738132)[0;0m INFO 09-10 14:56:59 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_a3824998'), local_subscribe_addr='ipc:///tmp/18bd27d8-0f76-484c-b1aa-9be4fbd7f17d', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m INFO 09-10 14:56:59 [parallel_state.py:1163] rank 1 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1, CP rank 0
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m INFO 09-10 14:56:59 [parallel_state.py:1163] rank 0 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0, CP rank 0
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738127)[0;0m INFO 09-10 14:56:59 [parallel_state.py:1163] rank 3 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 3, CP rank 1
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738147)[0;0m INFO 09-10 14:56:59 [parallel_state.py:1163] rank 7 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 7, CP rank 3
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738122)[0;0m INFO 09-10 14:56:59 [parallel_state.py:1163] rank 2 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 2, CP rank 1
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738137)[0;0m INFO 09-10 14:56:59 [parallel_state.py:1163] rank 5 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 5, CP rank 2
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738132)[0;0m INFO 09-10 14:56:59 [parallel_state.py:1163] rank 4 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 4, CP rank 2
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738142)[0;0m INFO 09-10 14:56:59 [parallel_state.py:1163] rank 6 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 6, CP rank 3
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m INFO 09-10 14:56:59 [model_runner_v1.py:2569] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m INFO 09-10 14:56:59 [model_runner_v1.py:2569] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738122)[0;0m INFO 09-10 14:56:59 [model_runner_v1.py:2569] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738132)[0;0m INFO 09-10 14:56:59 [model_runner_v1.py:2569] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738142)[0;0m INFO 09-10 14:56:59 [model_runner_v1.py:2569] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738147)[0;0m INFO 09-10 14:56:59 [model_runner_v1.py:2569] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738127)[0;0m INFO 09-10 14:56:59 [model_runner_v1.py:2569] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738137)[0;0m INFO 09-10 14:56:59 [model_runner_v1.py:2569] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m INFO 09-10 14:56:59 [layer.py:845] [EP Rank 0/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->0, 1->1, 2->2, 3->3, 4->4, 5->5, 6->6, 7->7.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738127)[0;0m INFO 09-10 14:57:00 [layer.py:845] [EP Rank 3/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->24, 1->25, 2->26, 3->27, 4->28, 5->29, 6->30, 7->31.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738147)[0;0m INFO 09-10 14:57:00 [layer.py:845] [EP Rank 7/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->56, 1->57, 2->58, 3->59, 4->60, 5->61, 6->62, 7->63.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738122)[0;0m INFO 09-10 14:57:00 [layer.py:845] [EP Rank 2/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->16, 1->17, 2->18, 3->19, 4->20, 5->21, 6->22, 7->23.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m INFO 09-10 14:57:00 [layer.py:845] [EP Rank 1/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->8, 1->9, 2->10, 3->11, 4->12, 5->13, 6->14, 7->15.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738132)[0;0m INFO 09-10 14:57:00 [layer.py:845] [EP Rank 4/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->32, 1->33, 2->34, 3->35, 4->36, 5->37, 6->38, 7->39.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738142)[0;0m INFO 09-10 14:57:00 [layer.py:845] [EP Rank 6/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->48, 1->49, 2->50, 3->51, 4->52, 5->53, 6->54, 7->55.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738137)[0;0m INFO 09-10 14:57:00 [layer.py:845] [EP Rank 5/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->40, 1->41, 2->42, 3->43, 4->44, 5->45, 6->46, 7->47.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738122)[0;0m INFO 09-10 14:57:03 [default_loader.py:267] Loading weights took 2.83 seconds
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m INFO 09-10 14:57:03 [default_loader.py:267] Loading weights took 3.01 seconds
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738127)[0;0m INFO 09-10 14:57:04 [default_loader.py:267] Loading weights took 2.98 seconds
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738132)[0;0m INFO 09-10 14:57:04 [default_loader.py:267] Loading weights took 2.97 seconds
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m INFO 09-10 14:57:04 [default_loader.py:267] Loading weights took 3.02 seconds
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738147)[0;0m INFO 09-10 14:57:04 [default_loader.py:267] Loading weights took 3.02 seconds
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738142)[0;0m INFO 09-10 14:57:04 [default_loader.py:267] Loading weights took 3.09 seconds
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738137)[0;0m INFO 09-10 14:57:04 [default_loader.py:267] Loading weights took 3.14 seconds
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738122)[0;0m INFO 09-10 14:57:05 [model_runner_v1.py:2599] Loading model weights took 5.3612 GB
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738127)[0;0m INFO 09-10 14:57:06 [model_runner_v1.py:2599] Loading model weights took 5.3612 GB
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738132)[0;0m INFO 09-10 14:57:06 [model_runner_v1.py:2599] Loading model weights took 5.3612 GB
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m INFO 09-10 14:57:06 [model_runner_v1.py:2599] Loading model weights took 5.3612 GB
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738147)[0;0m INFO 09-10 14:57:06 [model_runner_v1.py:2599] Loading model weights took 5.3612 GB
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m INFO 09-10 14:57:06 [model_runner_v1.py:2599] Loading model weights took 5.3612 GB
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738137)[0;0m INFO 09-10 14:57:06 [model_runner_v1.py:2599] Loading model weights took 5.3612 GB
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738142)[0;0m INFO 09-10 14:57:06 [model_runner_v1.py:2599] Loading model weights took 5.3612 GB
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738122)[0;0m INFO 09-10 14:57:12 [worker_v1.py:190] Available memory: 51520864256, total memory: 65787658240
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m INFO 09-10 14:57:12 [worker_v1.py:190] Available memory: 49659064115, total memory: 65796046848
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738137)[0;0m INFO 09-10 14:57:12 [worker_v1.py:190] Available memory: 16548719411, total memory: 65796046848
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738147)[0;0m INFO 09-10 14:57:12 [worker_v1.py:190] Available memory: 51790816051, total memory: 65796046848
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738142)[0;0m INFO 09-10 14:57:12 [worker_v1.py:190] Available memory: 4612106240, total memory: 65787658240
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738127)[0;0m INFO 09-10 14:57:12 [worker_v1.py:190] Available memory: 51916970803, total memory: 65796046848
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m INFO 09-10 14:57:12 [worker_v1.py:190] Available memory: 28394446848, total memory: 65787658240
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738132)[0;0m INFO 09-10 14:57:12 [worker_v1.py:190] Available memory: 51514194944, total memory: 65787658240
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:850] GPU KV cache size: 912,768 tokens
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:854] Maximum concurrency for 4,096 tokens per request: 1782.75x
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:850] GPU KV cache size: 1,596,544 tokens
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:854] Maximum concurrency for 4,096 tokens per request: 3118.25x
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:850] GPU KV cache size: 1,656,320 tokens
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:854] Maximum concurrency for 4,096 tokens per request: 3235.00x
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:850] GPU KV cache size: 1,669,120 tokens
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:854] Maximum concurrency for 4,096 tokens per request: 3260.00x
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:850] GPU KV cache size: 1,656,064 tokens
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:854] Maximum concurrency for 4,096 tokens per request: 3234.50x
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:850] GPU KV cache size: 531,968 tokens
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:854] Maximum concurrency for 4,096 tokens per request: 1039.00x
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:850] GPU KV cache size: 148,224 tokens
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:854] Maximum concurrency for 4,096 tokens per request: 289.50x
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:850] GPU KV cache size: 1,665,024 tokens
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:12 [kv_cache_utils.py:854] Maximum concurrency for 4,096 tokens per request: 3252.00x
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:13 [core.py:217] init engine (profile, create kv cache, warmup model) took 6.44 seconds
[1;36m(EngineCore_0 pid=738105)[0;0m WARNING 09-10 14:57:13 [core.py:110] Using configured V1 scheduler class vllm_ascend.core.scheduler.AscendScheduler. This scheduler interface is not public and compatibility may not be maintained.
[1;36m(EngineCore_0 pid=738105)[0;0m INFO 09-10 14:57:13 [platform.py:144] Compilation disabled, using eager mode by default
[1;36m(EngineCore_0 pid=738105)[0;0m WARNING 09-10 14:57:13 [platform.py:162] compilation_config.level = CompilationLevel.NO_COMPILATION is set, Setting CUDAGraphMode to NONE
INFO 09-10 14:57:13 [llm.py:285] Supported_tasks: ['generate']
INFO 09-10 14:57:13 [__init__.py:36] No IOProcessor plugins requested by the model
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738127)[0;0m WARNING 09-10 14:57:13 [cudagraph_dispatcher.py:102] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738142)[0;0m WARNING 09-10 14:57:13 [cudagraph_dispatcher.py:102] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m WARNING 09-10 14:57:13 [cudagraph_dispatcher.py:102] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738132)[0;0m WARNING 09-10 14:57:13 [cudagraph_dispatcher.py:102] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738122)[0;0m WARNING 09-10 14:57:13 [cudagraph_dispatcher.py:102] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m WARNING 09-10 14:57:13 [cudagraph_dispatcher.py:102] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738147)[0;0m WARNING 09-10 14:57:13 [cudagraph_dispatcher.py:102] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738137)[0;0m WARNING 09-10 14:57:13 [cudagraph_dispatcher.py:102] cudagraph dispatching keys are not initialized. No cudagraph will be used.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] WorkerProc hit an exception.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 608, in worker_busy_loop
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/worker_v1.py", line 205, in execute_model
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = self.model_runner.execute_model(scheduler_output,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 1973, in execute_model
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self._generate_process_reqs_hidden_states(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 1579, in _generate_process_reqs_hidden_states
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.model(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 1009, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.model(input_ids, positions, kv_caches,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 846, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states, residual = layer(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                               ^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 708, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.self_attn(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 607, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = self.mla_attn.impl.forward(hidden_states, kv_cache,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/attention/mla_v1.py", line 1522, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     decode_preprocess_res, prefill_preprocess_res = self._mla_preprocess(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                                                     ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/attention/mla_v1.py", line 1298, in _mla_preprocess
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     prefill_kv_c_k_pe = get_cp_group().all_gather(prefill_kv_c_k_pe, 0)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/parallel_state.py", line 389, in all_gather
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._all_gather_out_place(input_, dim)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/parallel_state.py", line 395, in _all_gather_out_place
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self.device_communicator.all_gather(input_, dim)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/device_communicators/base_device_communicator.py", line 130, in all_gather
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     dist.all_gather_into_tensor(output_tensor,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3836, in all_gather_into_tensor
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     work = group._allgather_base(output_tensor, input_tensor, opts)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] RuntimeError: InnerRunOpApi:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:281 OPS function error: HcclAllGather, error code is 2
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] [ERROR] 2025-09-10-14:57:14 (PID:738117, Device:1, RankID:-1) ERR01100 OPS call acl api failed.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] EL0004: [PID: 738117] 2025-09-10-14:57:14.060.233 Failed to allocate memory.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Possible Cause: Available memory is insufficient.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Solution: Close applications not in use.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         TraceBack (most recent call last):
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Failed to allocate resource[DeviceMemory] with info [size:209715200]. Reason: Memory resources are exhausted.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] 
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 608, in worker_busy_loop
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/worker_v1.py", line 205, in execute_model
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = self.model_runner.execute_model(scheduler_output,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 1973, in execute_model
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self._generate_process_reqs_hidden_states(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 1579, in _generate_process_reqs_hidden_states
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.model(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 1009, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.model(input_ids, positions, kv_caches,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 846, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states, residual = layer(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                               ^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 708, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.self_attn(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 607, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = self.mla_attn.impl.forward(hidden_states, kv_cache,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/attention/mla_v1.py", line 1522, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     decode_preprocess_res, prefill_preprocess_res = self._mla_preprocess(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                                                     ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/attention/mla_v1.py", line 1298, in _mla_preprocess
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     prefill_kv_c_k_pe = get_cp_group().all_gather(prefill_kv_c_k_pe, 0)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/parallel_state.py", line 389, in all_gather
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._all_gather_out_place(input_, dim)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/parallel_state.py", line 395, in _all_gather_out_place
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self.device_communicator.all_gather(input_, dim)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/device_communicators/base_device_communicator.py", line 130, in all_gather
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     dist.all_gather_into_tensor(output_tensor,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3836, in all_gather_into_tensor
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     work = group._allgather_base(output_tensor, input_tensor, opts)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] RuntimeError: InnerRunOpApi:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:281 OPS function error: HcclAllGather, error code is 2
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] [ERROR] 2025-09-10-14:57:14 (PID:738117, Device:1, RankID:-1) ERR01100 OPS call acl api failed.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] EL0004: [PID: 738117] 2025-09-10-14:57:14.060.233 Failed to allocate memory.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Possible Cause: Available memory is insufficient.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Solution: Close applications not in use.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         TraceBack (most recent call last):
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Failed to allocate resource[DeviceMemory] with info [size:209715200]. Reason: Memory resources are exhausted.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] 
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP1 pid=738117)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] 
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] WorkerProc hit an exception.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 608, in worker_busy_loop
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/worker_v1.py", line 205, in execute_model
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = self.model_runner.execute_model(scheduler_output,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 1973, in execute_model
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self._generate_process_reqs_hidden_states(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 1579, in _generate_process_reqs_hidden_states
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.model(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 1009, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.model(input_ids, positions, kv_caches,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 846, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states, residual = layer(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                               ^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 708, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.self_attn(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 607, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = self.mla_attn.impl.forward(hidden_states, kv_cache,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/attention/mla_v1.py", line 1522, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     decode_preprocess_res, prefill_preprocess_res = self._mla_preprocess(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                                                     ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/attention/mla_v1.py", line 1298, in _mla_preprocess
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     prefill_kv_c_k_pe = get_cp_group().all_gather(prefill_kv_c_k_pe, 0)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/parallel_state.py", line 389, in all_gather
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._all_gather_out_place(input_, dim)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/parallel_state.py", line 395, in _all_gather_out_place
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self.device_communicator.all_gather(input_, dim)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/device_communicators/base_device_communicator.py", line 130, in all_gather
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     dist.all_gather_into_tensor(output_tensor,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3836, in all_gather_into_tensor
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     work = group._allgather_base(output_tensor, input_tensor, opts)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] RuntimeError: InnerRunOpApi:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:281 OPS function error: HcclAllGather, error code is 2
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] [ERROR] 2025-09-10-14:57:14 (PID:738112, Device:0, RankID:-1) ERR01100 OPS call acl api failed.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] EL0004: [PID: 738112] 2025-09-10-14:57:14.148.454 Failed to allocate memory.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Possible Cause: Available memory is insufficient.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Solution: Close applications not in use.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         TraceBack (most recent call last):
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Failed to allocate resource[DeviceMemory] with info [size:209715200]. Reason: Memory resources are exhausted.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] 
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 608, in worker_busy_loop
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/worker_v1.py", line 205, in execute_model
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = self.model_runner.execute_model(scheduler_output,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 1973, in execute_model
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self._generate_process_reqs_hidden_states(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 1579, in _generate_process_reqs_hidden_states
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.model(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 1009, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.model(input_ids, positions, kv_caches,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 846, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states, residual = layer(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                               ^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 708, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     hidden_states = self.self_attn(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                     ^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._call_impl(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return forward_call(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 607, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     output = self.mla_attn.impl.forward(hidden_states, kv_cache,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/attention/mla_v1.py", line 1522, in forward
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     decode_preprocess_res, prefill_preprocess_res = self._mla_preprocess(
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                                                     ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm-ascend-origin/vllm_ascend/attention/mla_v1.py", line 1298, in _mla_preprocess
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     prefill_kv_c_k_pe = get_cp_group().all_gather(prefill_kv_c_k_pe, 0)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/parallel_state.py", line 389, in all_gather
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self._all_gather_out_place(input_, dim)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/parallel_state.py", line 395, in _all_gather_out_place
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return self.device_communicator.all_gather(input_, dim)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/home/vllm/vllm/distributed/device_communicators/base_device_communicator.py", line 130, in all_gather
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     dist.all_gather_into_tensor(output_tensor,
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3836, in all_gather_into_tensor
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]     work = group._allgather_base(output_tensor, input_tensor, opts)
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] RuntimeError: InnerRunOpApi:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:281 OPS function error: HcclAllGather, error code is 2
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] [ERROR] 2025-09-10-14:57:14 (PID:738112, Device:0, RankID:-1) ERR01100 OPS call acl api failed.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] EL0004: [PID: 738112] 2025-09-10-14:57:14.148.454 Failed to allocate memory.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Possible Cause: Available memory is insufficient.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Solution: Close applications not in use.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         TraceBack (most recent call last):
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613]         Failed to allocate resource[DeviceMemory] with info [size:209715200]. Reason: Memory resources are exhausted.
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] 
[1;36m(EngineCore_0 pid=738105)[0;0m [1;36m(VllmWorker TP0 pid=738112)[0;0m ERROR 09-10 14:57:14 [multiproc_executor.py:613] 
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [dump_input.py:69] Dumping input data for V1 LLM engine (v0.1.dev9076+ge80ce3c81) with config: model='/home/DeepSeek-V2-Lite', speculative_config=None, tokenizer='/home/DeepSeek-V2-Lite', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=npu, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/home/DeepSeek-V2-Lite, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["all"],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}, 
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [dump_input.py:76] Dumping scheduler output for model execution: SchedulerOutput(scheduled_new_reqs=[NewRequestData(req_id=0,prompt_token_ids_len=2446,mm_kwargs=[],mm_hashes=[],mm_positions=[],sampling_params=SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=0, min_p=0.0, seed=None, stop=[], stop_token_ids=[], bad_words=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=1, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None, guided_decoding=None, extra_args=None),block_ids=([1, 2, 3],),num_computed_tokens=0,lora_request=None)], scheduled_cached_reqs=CachedRequestData(req_ids=[], resumed_from_preemption=[], new_token_ids=[], new_block_ids=[], num_computed_tokens=[], kv_rank=[], num_computed_tokens_of_cp_sp=[]), num_scheduled_tokens={0: 2446}, total_num_scheduled_tokens=2446, scheduled_spec_decode_tokens={}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[0], finished_req_ids=[], free_encoder_mm_hashes=[], structured_output_request_ids={}, grammar_bitmask=null, kv_connector_metadata=null)
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714] EngineCore encountered a fatal error.
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]   File "/home/vllm/vllm/v1/engine/core.py", line 705, in run_engine_core
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]     engine_core.run_busy_loop()
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]   File "/home/vllm/vllm/v1/engine/core.py", line 732, in run_busy_loop
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]     self._process_engine_step()
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]   File "/home/vllm/vllm/v1/engine/core.py", line 758, in _process_engine_step
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]     outputs, model_executed = self.step_fn()
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]                               ^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]   File "/home/vllm/vllm/v1/engine/core.py", line 291, in step
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]     model_output = self.execute_model_with_error_logging(
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]   File "/home/vllm/vllm/v1/engine/core.py", line 277, in execute_model_with_error_logging
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]     raise err
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]   File "/home/vllm/vllm/v1/engine/core.py", line 268, in execute_model_with_error_logging
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]     return model_fn(scheduler_output)
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 175, in execute_model
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]     (output, ) = self.collective_rpc(
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]                  ^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 258, in collective_rpc
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]     result = get_response(w, dequeue_timeout)
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 242, in get_response
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]     raise RuntimeError(
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714] RuntimeError: Worker failed with error 'InnerRunOpApi:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:281 OPS function error: HcclAllGather, error code is 2
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714] [ERROR] 2025-09-10-14:57:14 (PID:738112, Device:0, RankID:-1) ERR01100 OPS call acl api failed.
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714] EL0004: [PID: 738112] 2025-09-10-14:57:14.148.454 Failed to allocate memory.
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]         Possible Cause: Available memory is insufficient.
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]         Solution: Close applications not in use.
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]         TraceBack (most recent call last):
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714]         Failed to allocate resource[DeviceMemory] with info [size:209715200]. Reason: Memory resources are exhausted.
[1;36m(EngineCore_0 pid=738105)[0;0m ERROR 09-10 14:57:14 [core.py:714] ', please check the stack trace above for the root cause
[ERROR] 2025-09-10-14:57:14 (PID:737834, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
