INFO 09-06 18:02:46 [__init__.py:36] Available plugins for group vllm.platform_plugins:
INFO 09-06 18:02:46 [__init__.py:38] - ascend -> vllm_ascend:register
INFO 09-06 18:02:46 [__init__.py:41] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 09-06 18:02:46 [__init__.py:232] Platform plugin ascend is activated
WARNING 09-06 18:02:48 [_custom_ops.py:20] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 09-06 18:02:48 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 09-06 18:02:50 [registry.py:464] Model architecture DeepSeekMTPModel is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_mtp:CustomDeepSeekMTP.
WARNING 09-06 18:02:50 [registry.py:464] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:AscendQwen2VLForConditionalGeneration.
WARNING 09-06 18:02:50 [registry.py:464] Model architecture Qwen2_5_VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_5_vl:AscendQwen2_5_VLForConditionalGeneration.
WARNING 09-06 18:02:50 [registry.py:464] Model architecture DeepseekV2ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV2ForCausalLM.
WARNING 09-06 18:02:50 [registry.py:464] Model architecture DeepseekV3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v3:CustomDeepseekV3ForCausalLM.
WARNING 09-06 18:02:50 [registry.py:464] Model architecture Qwen3MoeForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3_moe:CustomQwen3MoeForCausalLM.
WARNING 09-06 18:02:50 [registry.py:464] Model architecture Qwen3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3:CustomQwen3ForCausalLM.
INFO 09-06 18:02:50 [utils.py:326] non-default args: {'model': '/mnt/weight/deepseekv3-lite-base-latest', 'trust_remote_code': True, 'max_model_len': 4096, 'tensor_parallel_size': 2, 'context_parallel_size': 4, 'enable_sequence_parallel': True, 'enable_expert_parallel': True, 'block_size': 128, 'enable_prefix_caching': False, 'max_num_batched_tokens': 1024, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': True, 'additional_config': {'ascend_scheduler_config': {'enabled': True}}}
INFO 09-06 18:02:50 [config.py:240] Replacing legacy 'type' key with 'rope_type'
INFO 09-06 18:02:59 [__init__.py:742] Resolved architecture: DeepseekV3ForCausalLM
INFO 09-06 18:02:59 [__init__.py:1774] Using max model len 4096
INFO 09-06 18:02:59 [config.py:240] Replacing legacy 'type' key with 'rope_type'
INFO 09-06 18:02:59 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=1024.
INFO 09-06 18:02:59 [platform.py:156] Compilation disabled, using eager mode by default
[1;36m(EngineCore_0 pid=462474)[0;0m INFO 09-06 18:03:00 [core.py:644] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=462474)[0;0m INFO 09-06 18:03:00 [core.py:74] Initializing a V1 LLM engine (v0.1.dev8800+g376d98484.d20250901) with config: model='/mnt/weight/deepseekv3-lite-base-latest', speculative_config=None, tokenizer='/mnt/weight/deepseekv3-lite-base-latest', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=npu, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/mnt/weight/deepseekv3-lite-base-latest, enable_prefix_caching=False, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["all"],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=462474)[0;0m WARNING 09-06 18:03:00 [multiproc_worker_utils.py:273] Reducing Torch parallelism from 640 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[1;36m(EngineCore_0 pid=462474)[0;0m INFO 09-06 18:03:00 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1, 2, 3, 4, 5, 6, 7], buffer_handle=(8, 16777216, 10, 'psm_87153f00'), local_subscribe_addr='ipc:///tmp/37c817a7-05b3-41d6-a1d2-7aae3f78217e', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462481)[0;0m INFO 09-06 18:03:06 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_d6b977a9'), local_subscribe_addr='ipc:///tmp/c9119411-7099-4043-bccc-830459c4f84f', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462496)[0;0m INFO 09-06 18:03:06 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_8a0618b2'), local_subscribe_addr='ipc:///tmp/82e80a7d-9949-4c49-98d3-7c14ebfa0f10', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462486)[0;0m INFO 09-06 18:03:06 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_20594147'), local_subscribe_addr='ipc:///tmp/042c6230-a7b8-43aa-80c6-a6c6727f2278', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462516)[0;0m INFO 09-06 18:03:09 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_104c8268'), local_subscribe_addr='ipc:///tmp/0ae1c6fb-6467-45cf-94eb-4b020b6f69b6', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m INFO 09-06 18:03:10 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_410f29ae'), local_subscribe_addr='ipc:///tmp/1980efb1-b8de-4895-8368-e56f13ceab7a', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462511)[0;0m INFO 09-06 18:03:10 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_d6e1ef44'), local_subscribe_addr='ipc:///tmp/3de50abb-6a41-40f4-b2fa-bb22561d5095', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462506)[0;0m INFO 09-06 18:03:10 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_fc17a1d4'), local_subscribe_addr='ipc:///tmp/5548185d-76eb-40e9-be5c-781443969aa0', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462501)[0;0m INFO 09-06 18:03:11 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_3da1f265'), local_subscribe_addr='ipc:///tmp/2d6ca5e7-ff65-473b-a621-78ded34dd24a', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462481)[0;0m INFO 09-06 18:03:11 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_488fadde'), local_subscribe_addr='ipc:///tmp/1d174bf5-4e7e-4a18-964d-0f96ad190ddd', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462511)[0;0m INFO 09-06 18:03:11 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_c1383080'), local_subscribe_addr='ipc:///tmp/fbf8cedc-acad-4501-8c50-9afc35c1f7b0', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m INFO 09-06 18:03:11 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_e18414ed'), local_subscribe_addr='ipc:///tmp/1cfed7d0-1fc5-4ea1-a96e-f3b415efbf18', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462501)[0;0m INFO 09-06 18:03:11 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_5cd113a7'), local_subscribe_addr='ipc:///tmp/4ce0e5d2-d6d6-418b-8d43-9b6e5ac9c242', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462486)[0;0m INFO 09-06 18:03:11 [parallel_state.py:1163] rank 1 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1, CP rank 0
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m INFO 09-06 18:03:11 [parallel_state.py:1163] rank 2 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 2, CP rank 1
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462516)[0;0m INFO 09-06 18:03:11 [parallel_state.py:1163] rank 7 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 7, CP rank 3
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462511)[0;0m INFO 09-06 18:03:11 [parallel_state.py:1163] rank 6 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 6, CP rank 3
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462506)[0;0m INFO 09-06 18:03:11 [parallel_state.py:1163] rank 5 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 5, CP rank 2
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462501)[0;0m INFO 09-06 18:03:11 [parallel_state.py:1163] rank 4 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 4, CP rank 2
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462496)[0;0m INFO 09-06 18:03:11 [parallel_state.py:1163] rank 3 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 3, CP rank 1
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462481)[0;0m INFO 09-06 18:03:11 [parallel_state.py:1163] rank 0 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0, CP rank 0
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462516)[0;0m INFO 09-06 18:03:11 [model_runner_v1.py:2430] Starting to load model /mnt/weight/deepseekv3-lite-base-latest...
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462496)[0;0m INFO 09-06 18:03:11 [model_runner_v1.py:2430] Starting to load model /mnt/weight/deepseekv3-lite-base-latest...
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m INFO 09-06 18:03:11 [model_runner_v1.py:2430] Starting to load model /mnt/weight/deepseekv3-lite-base-latest...
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462511)[0;0m INFO 09-06 18:03:11 [model_runner_v1.py:2430] Starting to load model /mnt/weight/deepseekv3-lite-base-latest...
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462501)[0;0m INFO 09-06 18:03:11 [model_runner_v1.py:2430] Starting to load model /mnt/weight/deepseekv3-lite-base-latest...
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462486)[0;0m INFO 09-06 18:03:11 [model_runner_v1.py:2430] Starting to load model /mnt/weight/deepseekv3-lite-base-latest...
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462481)[0;0m INFO 09-06 18:03:11 [model_runner_v1.py:2430] Starting to load model /mnt/weight/deepseekv3-lite-base-latest...
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462506)[0;0m INFO 09-06 18:03:11 [model_runner_v1.py:2430] Starting to load model /mnt/weight/deepseekv3-lite-base-latest...
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462516)[0;0m INFO 09-06 18:03:12 [layer.py:828] [EP Rank 7/8] Expert parallelism is enabled. Local/global number of experts: 9/72. Experts local to global index map: 0->63, 1->64, 2->65, 3->66, 4->67, 5->68, 6->69, 7->70, 8->71.
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462496)[0;0m INFO 09-06 18:03:12 [layer.py:828] [EP Rank 3/8] Expert parallelism is enabled. Local/global number of experts: 9/72. Experts local to global index map: 0->27, 1->28, 2->29, 3->30, 4->31, 5->32, 6->33, 7->34, 8->35.
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462501)[0;0m INFO 09-06 18:03:12 [layer.py:828] [EP Rank 4/8] Expert parallelism is enabled. Local/global number of experts: 9/72. Experts local to global index map: 0->36, 1->37, 2->38, 3->39, 4->40, 5->41, 6->42, 7->43, 8->44.
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m INFO 09-06 18:03:12 [layer.py:828] [EP Rank 2/8] Expert parallelism is enabled. Local/global number of experts: 9/72. Experts local to global index map: 0->18, 1->19, 2->20, 3->21, 4->22, 5->23, 6->24, 7->25, 8->26.
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462481)[0;0m INFO 09-06 18:03:12 [layer.py:828] [EP Rank 0/8] Expert parallelism is enabled. Local/global number of experts: 9/72. Experts local to global index map: 0->0, 1->1, 2->2, 3->3, 4->4, 5->5, 6->6, 7->7, 8->8.
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462486)[0;0m INFO 09-06 18:03:12 [layer.py:828] [EP Rank 1/8] Expert parallelism is enabled. Local/global number of experts: 9/72. Experts local to global index map: 0->9, 1->10, 2->11, 3->12, 4->13, 5->14, 6->15, 7->16, 8->17.
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462511)[0;0m INFO 09-06 18:03:12 [layer.py:828] [EP Rank 6/8] Expert parallelism is enabled. Local/global number of experts: 9/72. Experts local to global index map: 0->54, 1->55, 2->56, 3->57, 4->58, 5->59, 6->60, 7->61, 8->62.
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP1 pid=462506)[0;0m INFO 09-06 18:03:12 [layer.py:828] [EP Rank 5/8] Expert parallelism is enabled. Local/global number of experts: 9/72. Experts local to global index map: 0->45, 1->46, 2->47, 3->48, 4->49, 5->50, 6->51, 7->52, 8->53.
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567] WorkerProc failed to start.
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 541, in worker_main
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     worker = WorkerProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 410, in __init__
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     self.worker.load_model()
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm-ascend-origin/vllm_ascend/worker/worker_v1.py", line 236, in load_model
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     self.model_runner.load_model()
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 2433, in load_model
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     self.model = get_model(vllm_config=self.vllm_config)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm/vllm/model_executor/model_loader/__init__.py", line 118, in get_model
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     return loader.load_model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm/vllm/model_executor/model_loader/base_loader.py", line 44, in load_model
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     model = initialize_model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm/vllm/model_executor/model_loader/utils.py", line 63, in initialize_model
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     return model_class(vllm_config=vllm_config, prefix=prefix)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 1057, in __init__
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     self.model = CustomDeepseekV2Model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 961, in __init__
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     self.start_layer, self.end_layer, self.layers = make_layers(
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]                                                     ^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm/vllm/model_executor/models/utils.py", line 640, in make_layers
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     [PPMissingLayer() for _ in range(start_layer)] + [
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]                                                      ^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm/vllm/model_executor/models/utils.py", line 641, in <listcomp>
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 963, in <lambda>
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     lambda prefix: CustomDeepseekV2DecoderLayer(
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 792, in __init__
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     self.mlp = CustomDeepseekV2MoE(
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]                ^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 407, in __init__
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     self.experts = AscendFusedMoE(
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]                    ^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm-ascend-origin/vllm_ascend/ops/fused_moe.py", line 1223, in __init__
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     self.quant_method.create_weights(layer=self, **moe_quant_params)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/home/vllm/vllm/model_executor/layers/fused_moe/layer.py", line 293, in create_weights
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     w13_weight = torch.nn.Parameter(torch.empty(
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]                                     ^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/utils/_device.py", line 104, in __torch_function__
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m [1;36m(VllmWorker TP0 pid=462491)[0;0m ERROR 09-06 18:03:15 [multiproc_executor.py:567] RuntimeError: NPU out of memory. Tried to allocate 136.00 MiB (NPU 2; 61.27 GiB total capacity; 8.36 GiB already allocated; 8.36 GiB current active; 41.19 MiB free; 8.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708] EngineCore failed to start.
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]   File "/home/vllm/vllm/v1/engine/core.py", line 699, in run_engine_core
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]   File "/home/vllm/vllm/v1/engine/core.py", line 500, in __init__
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]   File "/home/vllm/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]   File "/home/vllm/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]     self._init_executor()
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 98, in _init_executor
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]     self.workers = WorkerProc.wait_for_ready(unready_workers)
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 480, in wait_for_ready
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708]     raise e from None
[1;36m(EngineCore_0 pid=462474)[0;0m ERROR 09-06 18:03:17 [core.py:708] Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
[ERROR] 2025-09-06-18:03:17 (PID:462202, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
