INFO 09-10 11:20:17 [__init__.py:36] Available plugins for group vllm.platform_plugins:
INFO 09-10 11:20:17 [__init__.py:38] - ascend -> vllm_ascend:register
INFO 09-10 11:20:17 [__init__.py:41] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 09-10 11:20:17 [__init__.py:232] Platform plugin ascend is activated
WARNING 09-10 11:20:18 [_custom_ops.py:20] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 09-10 11:20:19 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 09-10 11:20:19 [registry.py:477] Model architecture DeepSeekMTPModel is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_mtp:CustomDeepSeekMTP.
WARNING 09-10 11:20:19 [registry.py:477] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:AscendQwen2VLForConditionalGeneration.
WARNING 09-10 11:20:19 [registry.py:477] Model architecture Qwen2_5_VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_5_vl:AscendQwen2_5_VLForConditionalGeneration.
WARNING 09-10 11:20:19 [registry.py:477] Model architecture DeepseekV2ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV2ForCausalLM.
WARNING 09-10 11:20:19 [registry.py:477] Model architecture DeepseekV3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v3:CustomDeepseekV3ForCausalLM.
WARNING 09-10 11:20:19 [registry.py:477] Model architecture Qwen3MoeForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3_moe:CustomQwen3MoeForCausalLM.
WARNING 09-10 11:20:19 [registry.py:477] Model architecture Qwen3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3:CustomQwen3ForCausalLM.
INFO 09-10 11:20:19 [utils.py:328] non-default args: {'trust_remote_code': True, 'max_model_len': 4096, 'tensor_parallel_size': 2, 'context_parallel_size': 4, 'enable_sequence_parallel': True, 'enable_expert_parallel': True, 'block_size': 128, 'enable_prefix_caching': False, 'max_num_batched_tokens': 1024, 'disable_log_stats': True, 'enforce_eager': True, 'enable_chunked_prefill': True, 'additional_config': {'ascend_scheduler_config': {'enabled': True}}, 'model': '/home/DeepSeek-V2-Lite'}
INFO 09-10 11:20:19 [config.py:234] Replacing legacy 'type' key with 'rope_type'
INFO 09-10 11:20:28 [__init__.py:744] Resolved architecture: DeepseekV2ForCausalLM
INFO 09-10 11:20:28 [__init__.py:1773] Using max model len 4096
INFO 09-10 11:20:28 [config.py:234] Replacing legacy 'type' key with 'rope_type'
INFO 09-10 11:20:28 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=1024.
INFO 09-10 11:20:28 [platform.py:144] Compilation disabled, using eager mode by default
WARNING 09-10 11:20:28 [platform.py:162] compilation_config.level = CompilationLevel.NO_COMPILATION is set, Setting CUDAGraphMode to NONE
[1;36m(EngineCore_0 pid=680478)[0;0m INFO 09-10 11:20:28 [core.py:648] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=680478)[0;0m INFO 09-10 11:20:28 [core.py:75] Initializing a V1 LLM engine (v0.1.dev9076+ge80ce3c81) with config: model='/home/DeepSeek-V2-Lite', speculative_config=None, tokenizer='/home/DeepSeek-V2-Lite', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=npu, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/home/DeepSeek-V2-Lite, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["all"],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=680478)[0;0m WARNING 09-10 11:20:28 [multiproc_worker_utils.py:273] Reducing Torch parallelism from 640 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[1;36m(EngineCore_0 pid=680478)[0;0m INFO 09-10 11:20:28 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1, 2, 3, 4, 5, 6, 7], buffer_handle=(8, 16777216, 10, 'psm_6843e6fd'), local_subscribe_addr='ipc:///tmp/77f05f59-31af-4715-9240-2117e76fac98', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680500)[0;0m INFO 09-10 11:20:39 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_c32c38e4'), local_subscribe_addr='ipc:///tmp/fde9967d-bf60-45af-b306-68498cd2bba7', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680488)[0;0m INFO 09-10 11:20:40 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_1820b9e7'), local_subscribe_addr='ipc:///tmp/814b0566-3775-458c-bfb6-f56589b8d7d2', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680510)[0;0m INFO 09-10 11:20:41 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_6a2b57b9'), local_subscribe_addr='ipc:///tmp/0e3c7271-6b05-4b4d-88db-781158d96de5', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680515)[0;0m INFO 09-10 11:20:43 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_6da11a9e'), local_subscribe_addr='ipc:///tmp/2e11b65c-d550-4c30-8a62-bc455888c49b', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m INFO 09-10 11:20:44 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_ece43208'), local_subscribe_addr='ipc:///tmp/65c6dcbe-5e32-4101-b173-1838847f34c3', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680495)[0;0m INFO 09-10 11:20:44 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_2220eac6'), local_subscribe_addr='ipc:///tmp/0f6e2181-288b-4b71-b6f5-06dc6f05068e', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680518)[0;0m INFO 09-10 11:20:44 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_cd32ed4e'), local_subscribe_addr='ipc:///tmp/50615a4e-8b52-4bea-97ab-7c7f400d5206', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680505)[0;0m INFO 09-10 11:20:44 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_cfbfa175'), local_subscribe_addr='ipc:///tmp/1f7e2eaf-0795-4645-8fcb-b284b38f72e6', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680505)[0;0m INFO 09-10 11:20:51 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_067b7695'), local_subscribe_addr='ipc:///tmp/efc75e6d-7459-4da4-8bf0-551922d426f5', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680515)[0;0m INFO 09-10 11:20:51 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_f9f70332'), local_subscribe_addr='ipc:///tmp/719ffb66-c968-44b4-8233-9497751d62e3', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680495)[0;0m INFO 09-10 11:20:51 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_f311f84a'), local_subscribe_addr='ipc:///tmp/9b440794-fe88-421a-91c6-c2192f71e695', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m INFO 09-10 11:20:51 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_775fd60e'), local_subscribe_addr='ipc:///tmp/5f519678-f04a-40a6-8410-053154b4d2c7', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m INFO 09-10 11:20:51 [parallel_state.py:1163] rank 0 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0, CP rank 0
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680488)[0;0m INFO 09-10 11:20:51 [parallel_state.py:1163] rank 1 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1, CP rank 0
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680505)[0;0m INFO 09-10 11:20:51 [parallel_state.py:1163] rank 4 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 4, CP rank 2
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680510)[0;0m INFO 09-10 11:20:51 [parallel_state.py:1163] rank 5 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 5, CP rank 2
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680515)[0;0m INFO 09-10 11:20:51 [parallel_state.py:1163] rank 6 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 6, CP rank 3
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680518)[0;0m INFO 09-10 11:20:51 [parallel_state.py:1163] rank 7 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 7, CP rank 3
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680500)[0;0m INFO 09-10 11:20:51 [parallel_state.py:1163] rank 3 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 3, CP rank 1
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680495)[0;0m INFO 09-10 11:20:51 [parallel_state.py:1163] rank 2 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 2, CP rank 1
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m INFO 09-10 11:20:51 [model_runner_v1.py:2563] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680518)[0;0m INFO 09-10 11:20:51 [model_runner_v1.py:2563] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680500)[0;0m INFO 09-10 11:20:51 [model_runner_v1.py:2563] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680488)[0;0m INFO 09-10 11:20:51 [model_runner_v1.py:2563] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680515)[0;0m INFO 09-10 11:20:51 [model_runner_v1.py:2563] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680510)[0;0m INFO 09-10 11:20:51 [model_runner_v1.py:2563] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680505)[0;0m INFO 09-10 11:20:51 [model_runner_v1.py:2563] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680495)[0;0m INFO 09-10 11:20:51 [model_runner_v1.py:2563] Starting to load model /home/DeepSeek-V2-Lite...
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m INFO 09-10 11:20:51 [layer.py:845] [EP Rank 0/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->0, 1->1, 2->2, 3->3, 4->4, 5->5, 6->6, 7->7.
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680488)[0;0m INFO 09-10 11:20:52 [layer.py:845] [EP Rank 1/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->8, 1->9, 2->10, 3->11, 4->12, 5->13, 6->14, 7->15.
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680500)[0;0m INFO 09-10 11:20:52 [layer.py:845] [EP Rank 3/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->24, 1->25, 2->26, 3->27, 4->28, 5->29, 6->30, 7->31.
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680518)[0;0m INFO 09-10 11:20:52 [layer.py:845] [EP Rank 7/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->56, 1->57, 2->58, 3->59, 4->60, 5->61, 6->62, 7->63.
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680495)[0;0m INFO 09-10 11:20:52 [layer.py:845] [EP Rank 2/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->16, 1->17, 2->18, 3->19, 4->20, 5->21, 6->22, 7->23.
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP1 pid=680510)[0;0m INFO 09-10 11:20:52 [layer.py:845] [EP Rank 5/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->40, 1->41, 2->42, 3->43, 4->44, 5->45, 6->46, 7->47.
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680515)[0;0m INFO 09-10 11:20:52 [layer.py:845] [EP Rank 6/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->48, 1->49, 2->50, 3->51, 4->52, 5->53, 6->54, 7->55.
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680505)[0;0m INFO 09-10 11:20:52 [layer.py:845] [EP Rank 4/8] Expert parallelism is enabled. Local/global number of experts: 8/64. Experts local to global index map: 0->32, 1->33, 2->34, 3->35, 4->36, 5->37, 6->38, 7->39.
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576] WorkerProc failed to start.
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 550, in worker_main
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     worker = WorkerProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 419, in __init__
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     self.worker.load_model()
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/worker/worker_v1.py", line 241, in load_model
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     self.model_runner.load_model()
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/worker/model_runner_v1.py", line 2566, in load_model
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     self.model = get_model(vllm_config=self.vllm_config)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/model_loader/__init__.py", line 118, in get_model
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     return loader.load_model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/model_loader/base_loader.py", line 44, in load_model
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     model = initialize_model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/model_loader/utils.py", line 63, in initialize_model
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     return model_class(vllm_config=vllm_config, prefix=prefix)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 878, in __init__
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     self.model = CustomDeepseekV2Model(vllm_config=vllm_config,
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 800, in __init__
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     self.start_layer, self.end_layer, self.layers = make_layers(
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]                                                     ^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/models/utils.py", line 642, in make_layers
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     [PPMissingLayer() for _ in range(start_layer)] + [
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]                                                      ^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/models/utils.py", line 643, in <listcomp>
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 802, in <lambda>
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     lambda prefix: CustomDeepseekV2DecoderLayer(
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 664, in __init__
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     self.mlp = CustomDeepseekV2MoE(
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]                ^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/models/deepseek_v2.py", line 337, in __init__
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     self.experts = AscendFusedMoE(
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]                    ^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm-ascend-origin/vllm_ascend/ops/fused_moe.py", line 232, in __init__
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     super().__init__(
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/layers/fused_moe/layer.py", line 937, in __init__
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     self.quant_method.create_weights(layer=self, **moe_quant_params)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/home/vllm/vllm/model_executor/layers/fused_moe/layer.py", line 296, in create_weights
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     w13_weight = torch.nn.Parameter(torch.empty(
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]                                     ^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/utils/_device.py", line 104, in __torch_function__
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m [1;36m(VllmWorker TP0 pid=680485)[0;0m ERROR 09-10 11:20:52 [multiproc_executor.py:576] RuntimeError: NPU out of memory. Tried to allocate 90.00 MiB (NPU 0; 61.27 GiB total capacity; 425.56 MiB already allocated; 425.56 MiB current active; 32.11 MiB free; 440.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712] EngineCore failed to start.
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]   File "/home/vllm/vllm/v1/engine/core.py", line 703, in run_engine_core
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]   File "/home/vllm/vllm/v1/engine/core.py", line 504, in __init__
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]   File "/home/vllm/vllm/v1/engine/core.py", line 81, in __init__
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]   File "/home/vllm/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]     self._init_executor()
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 98, in _init_executor
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]     self.workers = WorkerProc.wait_for_ready(unready_workers)
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]   File "/home/vllm/vllm/v1/executor/multiproc_executor.py", line 489, in wait_for_ready
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712]     raise e from None
[1;36m(EngineCore_0 pid=680478)[0;0m ERROR 09-10 11:20:55 [core.py:712] Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
[ERROR] 2025-09-10-11:20:55 (PID:680206, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
